# memory-index.ps1 - regenerate .memories/README.md from each memory file's frontmatter.
# The pre-commit hook runs this so the index can never be committed stale; safe to
# run by hand any time.
#
# Windows PowerShell 5.1's default encoding is the system codepage, not UTF-8; reading
# UTF-8 files (em dashes, curly quotes, etc.) without pinning -Encoding utf8 on
# Get-Content mangles them into mojibake ("â€”" for "—") the moment they're
# re-serialized into README.md. The write side uses [System.IO.File]::WriteAllText
# with an explicit no-BOM UTF8Encoding instead of Set-Content -Encoding utf8, since
# PowerShell 5.1's "utf8" Set-Content always emits a BOM.
[CmdletBinding()]
param(
    [string]$MemoriesDir
)

$ErrorActionPreference = 'Stop'

if (-not $MemoriesDir) {
    # tools/ sits directly under the repo root; .memories/ is its sibling.
    $MemoriesDir = Join-Path (Split-Path $PSScriptRoot -Parent) '.memories'
}

if (-not (Test-Path $MemoriesDir)) {
    Write-Error "Memories directory not found: $MemoriesDir"
    exit 1
}

function Get-FrontmatterValue {
    param([string[]]$Lines, [string]$Key)
    if ($Lines.Count -eq 0 -or $Lines[0].Trim() -ne '---') { return $null }
    for ($i = 1; $i -lt $Lines.Count; $i++) {
        if ($Lines[$i].Trim() -eq '---') { break }
        $m = [regex]::Match($Lines[$i], "^\s*$([regex]::Escape($Key))\s*:\s*(.*)$")
        if ($m.Success) {
            return $m.Groups[1].Value.Trim().Trim('"').Trim("'")
        }
    }
    return $null
}

$files = Get-ChildItem -Path $MemoriesDir -Filter '*.md' -File |
    Where-Object { $_.Name -ne 'README.md' } |
    Sort-Object Name

$lines = @(
    '# Memories index',
    '',
    'Project knowledge store: one fact per file, grep-friendly, committed and shared.',
    'Each file opens with `description:` frontmatter. This index is auto-generated by',
    '`tools/memory-index.ps1` (run by the pre-commit hook) -- do not hand-edit the list.',
    ''
)

if ($files.Count -eq 0) {
    $lines += '_(no memories yet -- add `.memories/<kebab-key>.md` files)_'
} else {
    foreach ($f in $files) {
        $key = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
        $content = Get-Content -LiteralPath $f.FullName -Encoding utf8
        $desc = Get-FrontmatterValue -Lines $content -Key 'description'
        if (-not $desc) { $desc = '(no description)' }
        $lines += ("- [{0}]({1}) -- {2}" -f $key, $f.Name, $desc)
    }
}

$readmePath = Join-Path $MemoriesDir 'README.md'
$noBomUtf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($readmePath, (($lines -join "`n") + "`n"), $noBomUtf8)
Write-Host ("memory-index: {0} entr{1} -> {2}" -f $files.Count, $(if ($files.Count -eq 1) { 'y' } else { 'ies' }), $readmePath)
